package in.gov.gramdrishti.entity;

public enum InfraType {
    ROAD,
    HEALTH_SUB_CENTRE,
    PRIMARY_HEALTH_CENTRE,
    PRIMARY_SCHOOL,
    SECONDARY_SCHOOL,
    WATER_OVERHEAD_TANK,
    WATER_TREATMENT_PLANT,
    TELECOM_TOWER,
    POWER_SUBSTATION,
    SOLAR_MICROGRID,
    APMC_MANDI,
    GRAM_PANCHAYAT_BHAVAN
}
